TaskBlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from TaskBlogApp import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/$', views.PostView.as_view(), name='post'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),

    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^sign_up/$', views.SignupView.as_view(), name='signup'),

    url(r'^add_post/$', views.AddPostView.as_view(), name='add_post'),
    url(r'^add_cat/$', views.AddCategoryView.as_view(), name='add_cat'),

    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/like_post/$', views.PlusLikePostView.as_view(),
        name='like_post'),
    url(r'^/category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/dislike_post/$', views.PlusDislikePostView.as_view(),
        name='dislike_post'),

    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/dislike_comment/(?P<comment_id>[0-9]+)/$',
        views.PlusDislikeCommentView.as_view(),
        name='dislike_comment'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/like_comment/(?P<comment_id>[0-9]+)/$',
        views.PluslikeCommentView.as_view(),
        name='like_comment'),

    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/edit/$', views.EditPostView.as_view(),
        name='edit_post'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/delete/$', views.DeletePostView.as_view(),
        name='delete_post'),

    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/comment/(?P<comment_id>[0-9]+)/edit/$',
        views.EditCommentView.as_view(),
        name='edit_comment'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete/$',
        views.DeleteCommentView.as_view(),
        name='delete_comment'),

    url(r'^category/(?P<id>[0-9]+)/delete/$', views.DeleteCatView.as_view(), name='delete_cat'),
    url(r'^profile/(?P<id>[0-9]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^profile/edit/(?P<id>[0-9]+)/$', views.EditProfileView.as_view(), name='edit-profile'),

    url(r'^api/', include('drf.urls', namespace='rest_framework')),
]

drf/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from drf import views

router = routers.DefaultRouter()
router.register(r'category', views.CategoryViewSet, base_name='category')
router.register(r'post', views.PostsViewSet, base_name='post')
router.register(r'comment', views.CommentViewSet, base_name='comment')
router.register(r'user', views.UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),

    url(r'^comment/(?P<id>[0-9]+)/like/$', views.CommentLikeViewSet.as_view({'get': 'get'}),
        name='comment-like'),
    url(r'^comment/(?P<id>[0-9]+)/dislike/$', views.CommentDislikeViewSet.as_view({'get': 'get'}),
        name='comment-dislike'),
    url(r'^post/(?P<id>[0-9]+)/like/$', views.PostLikeViewSet.as_view({'get': 'get'}),
        name='post-like'),
    url(r'^post/(?P<id>[0-9]+)/dislike/$', views.PostDislikeViewSet.as_view({'get': 'get'}),
        name='post-dislike'),

    url(r'^auth/', views.AuthViewSet.as_view({'post': 'post', 'delete': 'destroy'}), name='auth'),
]

TaskBlogApp/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Category(models.Model):
    cat_title = models.CharField(max_length=70)

    def __str__(self):
        return self.cat_title

@python_2_unicode_compatible
class Post(models.Model):
    post_cat = models.ForeignKey(Category)
    post_author = models.ForeignKey(User)

    post_title = models.CharField(max_length=70)
    post_content = models.TextField()

    post_createdAt = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    post_updatedAd = models.DateTimeField(auto_now_add=False, default=datetime.now)

    post_like = models.IntegerField(default=0)
    post_dislike = models.IntegerField(default=0)

    def __str__(self):
        return self.post_title


@python_2_unicode_compatible
class Comment(models.Model):
    comment_post = models.ForeignKey(Post)
    comment_author = models.ForeignKey(User)

    comment_content = models.CharField(max_length=100)
    comment_like = models.IntegerField(default=0)
    comment_dislike = models.IntegerField(default=0)

    comment_createdAt = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    comment_updatedAt = models.DateTimeField(auto_now_add=False, default=datetime.now)

    def __str__(self):
        return self.comment_content

templates/add_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
	<style type="text/css">
	body {padding-top: 70px;}
    footer {margin: 50px 0;}
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    Add Category
                </h1>
                <div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <p>{% if cat_form_error %}{{ cat_form_error }}{% endif %}</p>
                        <p>{{ cat_form.as_p }}</p>
                        <p><input type="submit" value="Add Category"></p>
                    </form>
                </div>
            </div>
        </div>
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Blog Task</p>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}
</body>
</html>

templates/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
	<style type="text/css">
	body {padding-top: 70px;}
    footer {margin: 50px 0;}
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    Add Post
                </h1>
                <form action="" method="post">
                {% csrf_token %}
                    <div>
                       <p>{% if post_error %} {{ post_error }} {% endif %}</p>
                                {{ add_post_form.as_p }}
                        <p><input type="submit" value="Add"></p>
                     </div>
                </form>
                <hr>
                <footer>
                    <div class="row">
                        <div class="col-lg-12">
                            <p>Blog Task</p>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
	<style type="text/css">
	body {padding-top: 70px;} footer {margin: 50px 0;}
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <a href="{% url 'delete_cat' cat_pk %}">Delete</a>
                {% for post in posts %}
                    <h2>
                        <a href="{% url 'post' post.post_cat_id post.id %}">{{ post.post_title }}</a>
                        <small style="float:right">{{ post.post_cat }}</small>
                    </h2>
                    <p class="lead">
                        by <a href="">{{ post.post_author }}</a>
                    </p>
                    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.post_updatedAd }}</p>
                    <p>{{ post.post_content|slice:":300" }}...</p>
                    <a class="btn btn-primary" href="{% url 'post' post.post_cat_id post.id %}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                    <hr>
                {% endfor %}
            </div>
            <div class="col-md-4">
            </div>
        </div>
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Blog Task</p>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}
</body>
</html>

templates/edit-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"/>
    <style type="text/css">
        body {
            padding-top: 70px;
        }

        footer {
            margin: 50px 0;
        }
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">Edit {{ user.username }} profile</div>
                    <div class="panel-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <table>
                                {% if edit_form_error %}
                                    <tr style="padding-bottom: 2px;">
                                        <td>{{ edit_form_error }}</td>
                                    </tr>
                                {% endif %}
                                <tr style="padding-bottom: 2px;">
                                    <td><label for="username">Username :</label></td>
                                    <td>{{ edit_form.username }}</td>
                                    <td><span style="color: #777; margin-left: 5px;">{{ user.username }}</span></td>
                                </tr>
                                <tr style="padding-bottom: 2px;">
                                    <td><label for="email">Email</label></td>
                                    <td>{{ edit_form.email }}</td>
                                    <td><span style="color: #777; margin-left: 5px;">{{ user.email }}</span></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td><input type="submit" value="Save" style="float:right"></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <hr>
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Blog Task</p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/editComment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
	<style type="text/css">
	body {padding-top: 70px;}
    footer {margin: 50px 0;}
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    Edit Comment
                </h1>
                <form action="" method="post">
                {% csrf_token %}
                    <div>
                       <p>{% if form_error %} {{ post_error }} {% endif %}</p>
                                {{ form.as_p }}
                        <p><input type="submit" value="Add"></p>
                     </div>
                </form>
                <hr>
                <footer>
                    <div class="row">
                        <div class="col-lg-12">
                            <p>Blog Task</p>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/editPost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
	<style type="text/css">
	body {padding-top: 70px;}
    footer {margin: 50px 0;}
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    Edit Post
                    <small>Lastest Post</small>
                </h1>
                <form action="" method="post">
                {% csrf_token %}
                    <div>
                       <p>{% if post_form_error %} {{ post_error }} {% endif %}</p>
                                {{ post_form.as_p }}
                        <p><input type="submit" value="Add"></p>
                     </div>
                </form>
                <hr>
                <footer>
                    <div class="row">
                        <div class="col-lg-12">
                            <p>Blog Task</p>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/header.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Hello {{ user.first_name }} {{ user.last_name }}

                {% if user.is_authenticated %}
                    <span>{% if user.is_superuser %}(superuser) {% else %}(user){% endif %}</span>
                {% endif %}
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div>

            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}">Home Page</a></li>
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                {% else %}
                    {% if user.is_superuser %}
                        <li><a href="{% url 'add_cat' %}">Add Cat</a></li>
                        <li><a href="{% url 'add_post' %}">Add Post</a></li>
                    {% else %}
                        <li><a href="{% url 'add_post' %}">Add Post</a></li>
                    {% endif %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% endif %}
                <li><a href="{% url 'search' %}">Search</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"/>
    <style type="text/css">
        body {
            padding-top: 70px;
        }

        footer {
            margin: 50px 0;
        }
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    Home Page
                    <small>Lastest Post</small>
                </h1>
                {% for post in posts %}
                    <h2>
                        <a href="{% url 'post' post.post_cat_id post.id %}">{{ post.post_title }}</a>
                        <small style="float:right">{{ post.post_cat }}</small>
                    </h2>
                    <p class="lead">
                        by <a href="{% url 'profile' post.post_author_id %}">{{ post.post_author }}</a>
                    </p>
                    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.post_updatedAd }}</p>

                    <p>{{ post.post_content|slice:":300" }}...</p>
                    <a class="btn btn-primary" href="{% url 'post' post.post_cat_id post.id %}">Read More <span
                            class="glyphicon glyphicon-chevron-right"></span></a>
                    <hr>
                {% endfor %}
            </div>
            <div class="col-md-4">

                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-10">
                            <ul class="list-group">
                                {% if categories == None %}
                                    No Post. Be the first to add.
                                {% else %}
                                    {% for category in categories %}
                                        <li class="list-group-item">
                                            <span class="badge">{{ category.post_set.count }}</span>
                                            <a href="{% url 'category' category.id %}">{{ category.cat_title }}</a>
                                        </li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Blog Task</p>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
	<style type="text/css">
	body {padding-top: 70px;}
    footer {margin: 50px 0;}
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    Login Page
                </h1>
                <div>
                    <form action="" method="post">
                    {% csrf_token %}
                        <p>{{ login_error }}</p>
                        {{ login_form.as_p }}
                        <p><input type="submit" value="Login"></p>
                    </form>
                </div>
            </div>

        </div>
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Blog Task</p>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}
</body>
</html>

templates/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Blog Post - Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
	<style type="text/css">
	body {
    padding-top: 70px; /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    footer {
        margin: 50px 0;
    }
</style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
                <!-- Blog Post -->
                <!-- Title -->
                {% if not post %}
                    No Post.
                {% endif %}
                <h1>{{ post.post_title }}</h1>
                <!-- Author -->
                <p class="lead">
                    by <a href="{% url 'profile' post.post_author_id %}">{{ post.post_author }}</a>
                    <span style="float: right;"> <a href="{% url 'category' post.post_cat_id %}">{{ post.post_cat.cat_title }}</a></span>
                </p>
                <hr>
                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.post_createdAt }}
                <span style="float: right">Like : {{ post.post_like }} Dislike : {{ post.post_dislike }}</span>
                </p>
                <hr>
                <p>{{ post.post_content }}</p>
                <div style="float: left">
                {% if user.is_superuser %}
                    <a href="{% url 'delete_post' post.post_cat_id post.pk %}">Delete</a>
                    <a href="{% url 'edit_post' post.post_cat_id post.pk %}">Edit</a>
                {% else %}
                    {% if post.post_author_id == request.user.id %}
                        <a href="{% url 'delete_post' post.post_cat_id post.pk %}">Delete</a>
                        <a href="{% url 'edit_post' post.post_cat_id post.pk %}">Edit</a>
                    {% endif %}
                {% endif %}
                    <br><span class="glyphicon glyphicon-time"></span> Update at {{ post.post_updatedAd }}
                </div>
                <div style="text-align: right" style="float: left">
                    <a href="{% url 'like_post' post.post_cat_id post.pk %}">Like</a> |
                    <a href="{% url 'dislike_post' post.post_cat_id post.pk %}">Dislike</a></div>
                <hr>
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <p>{% if comment_form_error %}{{ comment_form.errors }} {% endif %}</p>
                            {{ comment_form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary">Add Comment</button>
                    </form>
                </div>
                <hr>
            {% if post.comment_set %}
                {% for comment in post.comment_set.all|dictsortreversed:"comment_updatedAt" %}
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">{{ comment.comment_author }}
                            <small>{{ comment.comment_updatedAt }}</small>
                            <div style="float: right;">
                                <small>Like : {{ comment.comment_like }}</small>
                                <small>Dislike : {{ comment.comment_dislike }}</small>
                            </div>
                        </h4>
                        {{ comment.comment_content }} <br>
                        <div>
                            <div style="float: left;">
                                {% if user.is_superuser %}
                                <a href="{% url 'edit_comment' comment.comment_post.post_cat_id comment.comment_post_id comment.id %}">Edit</a>
                                <a href="{% url 'delete_comment' comment.comment_post.post_cat_id comment.comment_post_id comment.id %}">Delete</a>
                                {% else %}
                                {% if request.user.id == comment.comment_author_id  %}
                                <a href="{% url 'edit_comment' comment.comment_post.post_cat_id comment.comment_post_id comment.id %}">Edit</a>
                                <a href="{% url 'delete_comment' comment.comment_post.post_cat_id comment.comment_post_id comment.id %}">Delete</a>
                                {% endif %}
                            {% endif %}
                            </div>
                            <div style="float: right;">
                            <small><a href="{% url 'like_comment' comment.comment_post.post_cat_id comment.comment_post_id comment.id  %}">Like</a></small> |
                            <small><a href="{% url 'dislike_comment' comment.comment_post.post_cat_id comment.comment_post_id comment.id  %}">Dislike</a></small>
                            </div>
                            </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            </div>
        </div>
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Blog Task</p>
                </div>
            </div>
        </footer>
    </div>
{% endblock content %}
</body>
</html>

templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Home - Start Bootstrap Template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
	<style type="text/css">
	body {padding-top: 70px;}
    footer {margin: 50px 0;}
    </style>
</head>
<body>
{% extends 'header.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    Signup Page
                </h1>
                <div>
                    <form action="" method="post">
                    {% csrf_token %}
                        {% if sign_error %}
                            <p>{{ sign_error }}</p>
                        {% endif %}
                        {{ sign_form.as_p }}
                        <p><input type="submit" value="Sign Up"></p>
                    </form>
                </div>

        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Blog Task</p>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}
</body>
</html>